language: go
os:
    - linux
go:
    - 1.15.x

before_script:
    - ulimit -n 30000

before_install:
    - go get -t -v ./...

install:
    - go get github.com/xtaci/gaio

script:
    - go test -coverprofile=coverage.txt -covermode=atomic -v -bench .

after_success:
    - bash <(curl -s https://codecov.io/bash)
